version: '3.7'
services:
    reverse-proxy:
        container_name: reverse-proxy
        image: 192.168.1.16:7878/reverse-proxy
        build:
            context: .
        ports:
            - '7000:8080'
            - '7001:8081'
            - '7002:9000'
        deploy:
            mode: global